// ============================================================
// DATA.JS — Dados mock do CRM de Materiais de Construção B2B
// ============================================================

const PRODUTOS = [
  { id: 'p1', nome: 'Cimento CP-II 50kg', categoria: 'Cimentos', preco_unitario: 38.90 },
  { id: 'p2', nome: 'Vergalhão CA-50 12mm', categoria: 'Aço e Ferro', preco_unitario: 210.00 },
  { id: 'p3', nome: 'Tijolo Cerâmico 6F', categoria: 'Alvenaria', preco_unitario: 0.95 },
  { id: 'p4', nome: 'Tinta Acrílica Fosca 18L', categoria: 'Tintas', preco_unitario: 189.00 },
  { id: 'p5', nome: 'Tubo PVC 100mm x 6m', categoria: 'Hidráulica', preco_unitario: 42.50 },
  { id: 'p6', nome: 'Lona Plástica 200 micras', categoria: 'Impermeabilização', preco_unitario: 320.00 },
  { id: 'p7', nome: 'Telha Ondulada Fibrocimento', categoria: 'Coberturas', preco_unitario: 28.90 },
  { id: 'p8', nome: 'Areia Média (m³)', categoria: 'Agregados', preco_unitario: 115.00 },
  { id: 'p9', nome: 'Perfil de Aço Galvanizado', categoria: 'Aço e Ferro', preco_unitario: 87.50 },
  { id: 'p10', nome: 'Argamassa Colante AC-II', categoria: 'Argamassas', preco_unitario: 24.90 },
];

const VENDEDORES = [
  { id: 'v1', nome: 'Ricardo Mendes', avatar: 'RM', cor: '#6366f1' },
  { id: 'v2', nome: 'Patrícia Souza', avatar: 'PS', cor: '#f97316' },
  { id: 'v3', nome: 'Felipe Andrade', avatar: 'FA', cor: '#10b981' },
  { id: 'v4', nome: 'Camila Torres', avatar: 'CT', cor: '#8b5cf6' },
];

const CLIENTES = [
  {
    id: 'c1',
    razao_social: 'Construtora Horizonte Ltda',
    nome_fantasia: 'Horizonte Obras',
    cnpj: '12.345.678/0001-90',
    tipo: 'Construtora',
    segmento: 'Residencial',
    cidade: 'São Paulo',
    estado: 'SP',
    responsavel_nome: 'Carlos Eduardo Lima',
    responsavel_cargo: 'Gerente de Compras',
    responsavel_email: 'compras@horizonteobras.com.br',
    responsavel_telefone: '(11) 98765-4321',
    limite_credito: 250000,
    status: 'Ativo',
    vendedor_id: 'v1',
    data_cadastro: '2024-03-15',
    ticket_medio: 48500,
    total_pedidos: 8,
  },
  {
    id: 'c2',
    razao_social: 'Empreiteira Vidal & Filhos S.A.',
    nome_fantasia: 'Vidal Construções',
    cnpj: '23.456.789/0001-01',
    tipo: 'Empreiteira',
    segmento: 'Comercial',
    cidade: 'Campinas',
    estado: 'SP',
    responsavel_nome: 'Marcos Vidal',
    responsavel_cargo: 'Diretor',
    responsavel_email: 'marcos@vidalconstrucoes.com.br',
    responsavel_telefone: '(19) 97654-3210',
    limite_credito: 180000,
    status: 'Ativo',
    vendedor_id: 'v2',
    data_cadastro: '2024-01-22',
    ticket_medio: 32000,
    total_pedidos: 12,
  },
  {
    id: 'c3',
    razao_social: 'Revenda MatCon Comércio Ltda',
    nome_fantasia: 'MatCon Materiais',
    cnpj: '34.567.890/0001-12',
    tipo: 'Revendedor',
    segmento: 'Varejo',
    cidade: 'Rio de Janeiro',
    estado: 'RJ',
    responsavel_nome: 'Fernanda Alves',
    responsavel_cargo: 'Sócia-Proprietária',
    responsavel_email: 'fernanda@matconmateriais.com.br',
    responsavel_telefone: '(21) 96543-2109',
    limite_credito: 120000,
    status: 'Ativo',
    vendedor_id: 'v3',
    data_cadastro: '2023-11-05',
    ticket_medio: 21500,
    total_pedidos: 19,
  },
  {
    id: 'c4',
    razao_social: 'Engenharia Estrutural BR S.A.',
    nome_fantasia: 'EngBR',
    cnpj: '45.678.901/0001-23',
    tipo: 'Construtora',
    segmento: 'Industrial',
    cidade: 'Belo Horizonte',
    estado: 'MG',
    responsavel_nome: 'Roberto Nunes',
    responsavel_cargo: 'Engenheiro de Suprimentos',
    responsavel_email: 'suprimentos@engbr.com.br',
    responsavel_telefone: '(31) 95432-1098',
    limite_credito: 500000,
    status: 'Ativo',
    vendedor_id: 'v1',
    data_cadastro: '2023-08-10',
    ticket_medio: 95000,
    total_pedidos: 6,
  },
  {
    id: 'c5',
    razao_social: 'Incorporadora Sol Nascente Ltda',
    nome_fantasia: 'Sol Nascente',
    cnpj: '56.789.012/0001-34',
    tipo: 'Incorporadora',
    segmento: 'Residencial',
    cidade: 'Curitiba',
    estado: 'PR',
    responsavel_nome: 'Ana Paula Ferreira',
    responsavel_cargo: 'Diretora de Operações',
    responsavel_email: 'ana@solnascente.com.br',
    responsavel_telefone: '(41) 94321-0987',
    limite_credito: 350000,
    status: 'Ativo',
    vendedor_id: 'v4',
    data_cadastro: '2024-02-28',
    ticket_medio: 72000,
    total_pedidos: 4,
  },
  {
    id: 'c6',
    razao_social: 'Casa & Obra Materiais Ltda',
    nome_fantasia: 'Casa & Obra',
    cnpj: '67.890.123/0001-45',
    tipo: 'Revendedor',
    segmento: 'Varejo',
    cidade: 'Porto Alegre',
    estado: 'RS',
    responsavel_nome: 'João Batista Costa',
    responsavel_cargo: 'Comprador',
    responsavel_email: 'compras@casaeobra.com.br',
    responsavel_telefone: '(51) 93210-9876',
    limite_credito: 90000,
    status: 'Inativo',
    vendedor_id: 'v2',
    data_cadastro: '2023-05-14',
    ticket_medio: 15000,
    total_pedidos: 22,
  },
  {
    id: 'c7',
    razao_social: 'Grupo Predial Nordeste S.A.',
    nome_fantasia: 'Predial NE',
    cnpj: '78.901.234/0001-56',
    tipo: 'Construtora',
    segmento: 'Residencial',
    cidade: 'Fortaleza',
    estado: 'CE',
    responsavel_nome: 'Sílvio Rodrigues',
    responsavel_cargo: 'Gerente de Suprimentos',
    responsavel_email: 'suprimentos@predialne.com.br',
    responsavel_telefone: '(85) 92109-8765',
    limite_credito: 420000,
    status: 'Ativo',
    vendedor_id: 'v3',
    data_cadastro: '2024-04-02',
    ticket_medio: 85000,
    total_pedidos: 3,
  },
  {
    id: 'c8',
    razao_social: 'Distribuidora Alfa Construção Ltda',
    nome_fantasia: 'Alfa Construção',
    cnpj: '89.012.345/0001-67',
    tipo: 'Distribuidor',
    segmento: 'Atacado',
    cidade: 'Salvador',
    estado: 'BA',
    responsavel_nome: 'Luciana Martins',
    responsavel_cargo: 'Gerente Comercial',
    responsavel_email: 'luciana@alfaconstrucao.com.br',
    responsavel_telefone: '(71) 91098-7654',
    limite_credito: 600000,
    status: 'Ativo',
    vendedor_id: 'v1',
    data_cadastro: '2023-09-20',
    ticket_medio: 130000,
    total_pedidos: 9,
  },
  {
    id: 'c9',
    razao_social: 'Construtora Três Lagoas ME',
    nome_fantasia: 'Três Lagoas Obras',
    cnpj: '90.123.456/0001-78',
    tipo: 'Construtora',
    segmento: 'Residencial',
    cidade: 'Goiânia',
    estado: 'GO',
    responsavel_nome: 'Paulo Henrique Dias',
    responsavel_cargo: 'Sócio',
    responsavel_email: 'paulo@treslagoas.com.br',
    responsavel_telefone: '(62) 90987-6543',
    limite_credito: 75000,
    status: 'Ativo',
    vendedor_id: 'v4',
    data_cadastro: '2024-05-11',
    ticket_medio: 18000,
    total_pedidos: 2,
  },
  {
    id: 'c10',
    razao_social: 'SuperObra Materiais S.A.',
    nome_fantasia: 'SuperObra',
    cnpj: '01.234.567/0001-89',
    tipo: 'Revendedor',
    segmento: 'Varejo',
    cidade: 'Manaus',
    estado: 'AM',
    responsavel_nome: 'Tatiana Pinheiro',
    responsavel_cargo: 'Diretora',
    responsavel_email: 'tatiana@superobra.com.br',
    responsavel_telefone: '(92) 89876-5432',
    limite_credito: 200000,
    status: 'Ativo',
    vendedor_id: 'v2',
    data_cadastro: '2023-12-01',
    ticket_medio: 38000,
    total_pedidos: 7,
  },
  {
    id: 'c11',
    razao_social: 'Empreiteira Minas Gerais Construções Ltda',
    nome_fantasia: 'MG Construções',
    cnpj: '11.223.344/0001-90',
    tipo: 'Empreiteira',
    segmento: 'Infraestrutura',
    cidade: 'Uberlândia',
    estado: 'MG',
    responsavel_nome: 'Gustavo Lopes',
    responsavel_cargo: 'Gerente de Compras',
    responsavel_email: 'compras@mgconstrucoes.com.br',
    responsavel_telefone: '(34) 88765-4321',
    limite_credito: 280000,
    status: 'Ativo',
    vendedor_id: 'v3',
    data_cadastro: '2024-01-08',
    ticket_medio: 55000,
    total_pedidos: 5,
  },
  {
    id: 'c12',
    razao_social: 'BuildTech Engenharia S.A.',
    nome_fantasia: 'BuildTech',
    cnpj: '22.334.455/0001-01',
    tipo: 'Construtora',
    segmento: 'Industrial',
    cidade: 'Recife',
    estado: 'PE',
    responsavel_nome: 'Rodrigo Cavalcanti',
    responsavel_cargo: 'CEO',
    responsavel_email: 'rodrigo@buildtech.com.br',
    responsavel_telefone: '(81) 77654-3210',
    limite_credito: 800000,
    status: 'Ativo',
    vendedor_id: 'v4',
    data_cadastro: '2023-10-30',
    ticket_medio: 185000,
    total_pedidos: 4,
  },
];

const OPORTUNIDADES = [
  {
    id: 'o1',
    titulo: 'Fornecimento de Cimento – Obra Residencial Fase 2',
    cliente_id: 'c1',
    vendedor_id: 'v1',
    produto_principal_id: 'p1',
    valor_estimado: 62000,
    fase: 'Negociação',
    probabilidade: 70,
    data_abertura: '2026-05-10',
    data_prevista: '2026-07-30',
    proxima_acao: 'Enviar contraproposta de desconto por volume',
    prioridade: 'Alta',
    produtos: ['p1', 'p8', 'p10'],
    atividades: [
      { tipo: 'Ligação', data: '2026-06-20', descricao: 'Alinhamento sobre tabela de preços de cimento. Cliente pediu 5% de desconto adicional.', usuario: 'Ricardo Mendes' },
      { tipo: 'Email', data: '2026-06-15', descricao: 'Envio da proposta comercial com preços atualizados.', usuario: 'Ricardo Mendes' },
      { tipo: 'Reunião', data: '2026-06-05', descricao: 'Reunião presencial na sede do cliente. Levantamento de necessidades para a Fase 2.', usuario: 'Ricardo Mendes' },
    ],
  },
  {
    id: 'o2',
    titulo: 'Kit Estrutural – Galpão Industrial 3000m²',
    cliente_id: 'c4',
    vendedor_id: 'v1',
    produto_principal_id: 'p2',
    valor_estimado: 145000,
    fase: 'Proposta',
    probabilidade: 50,
    data_abertura: '2026-05-20',
    data_prevista: '2026-08-15',
    proxima_acao: 'Apresentar proposta revisada com prazo de entrega',
    prioridade: 'Alta',
    produtos: ['p2', 'p9', 'p7'],
    atividades: [
      { tipo: 'Email', data: '2026-06-18', descricao: 'Cliente solicitou revisão nos prazos de entrega dos vergalhões.', usuario: 'Ricardo Mendes' },
      { tipo: 'Reunião', data: '2026-06-08', descricao: 'Visita ao canteiro de obras. Medição e levantamento técnico.', usuario: 'Ricardo Mendes' },
    ],
  },
  {
    id: 'o3',
    titulo: 'Reposição de Estoque – Tintas e Acabamentos',
    cliente_id: 'c3',
    vendedor_id: 'v3',
    produto_principal_id: 'p4',
    valor_estimado: 28500,
    fase: 'Qualificação',
    probabilidade: 35,
    data_abertura: '2026-06-01',
    data_prevista: '2026-07-15',
    proxima_acao: 'Enviar amostras e tabela de cores para aprovação',
    prioridade: 'Média',
    produtos: ['p4', 'p10'],
    atividades: [
      { tipo: 'Ligação', data: '2026-06-22', descricao: 'Primeiro contato. Cliente interessado em expandir linha de tintas.', usuario: 'Felipe Andrade' },
    ],
  },
  {
    id: 'o4',
    titulo: 'Contrato Anual – Materiais Hidráulicos',
    cliente_id: 'c8',
    vendedor_id: 'v1',
    produto_principal_id: 'p5',
    valor_estimado: 210000,
    fase: 'Fechado Ganho',
    probabilidade: 100,
    data_abertura: '2026-03-01',
    data_prevista: '2026-06-01',
    proxima_acao: 'Iniciar entregas conforme cronograma',
    prioridade: 'Alta',
    produtos: ['p5', 'p6'],
    atividades: [
      { tipo: 'Email', data: '2026-05-28', descricao: 'Contrato assinado digitalmente. Confirmação de recebimento.', usuario: 'Ricardo Mendes' },
      { tipo: 'Reunião', data: '2026-05-20', descricao: 'Reunião de fechamento com diretoria da Alfa Construção.', usuario: 'Ricardo Mendes' },
      { tipo: 'Proposta', data: '2026-04-15', descricao: 'Envio da proposta final com condições especiais para contrato anual.', usuario: 'Ricardo Mendes' },
    ],
  },
  {
    id: 'o5',
    titulo: 'Lote de Tijolos – Condomínio Recanto Verde',
    cliente_id: 'c5',
    vendedor_id: 'v4',
    produto_principal_id: 'p3',
    valor_estimado: 47000,
    fase: 'Prospecção',
    probabilidade: 20,
    data_abertura: '2026-06-20',
    data_prevista: '2026-09-01',
    proxima_acao: 'Agendar visita técnica ao empreendimento',
    prioridade: 'Baixa',
    produtos: ['p3', 'p8'],
    atividades: [
      { tipo: 'Ligação', data: '2026-06-25', descricao: 'Indicação de contato pela diretoria. Conversa inicial sobre projeto.', usuario: 'Camila Torres' },
    ],
  },
  {
    id: 'o6',
    titulo: 'Fornecimento de Vergalhões – Infraestrutura CE',
    cliente_id: 'c7',
    vendedor_id: 'v3',
    produto_principal_id: 'p2',
    valor_estimado: 98000,
    fase: 'Negociação',
    probabilidade: 65,
    data_abertura: '2026-04-15',
    data_prevista: '2026-07-20',
    proxima_acao: 'Definir condições de pagamento parcelado',
    prioridade: 'Alta',
    produtos: ['p2', 'p9'],
    atividades: [
      { tipo: 'Email', data: '2026-06-21', descricao: 'Contraproposta de pagamento: 30/60/90 dias.', usuario: 'Felipe Andrade' },
      { tipo: 'Reunião', data: '2026-06-10', descricao: 'Reunião de negociação por vídeo. Discussão de volumes e prazos.', usuario: 'Felipe Andrade' },
      { tipo: 'Proposta', data: '2026-05-28', descricao: 'Proposta inicial enviada com desconto de 3% sobre tabela.', usuario: 'Felipe Andrade' },
    ],
  },
  {
    id: 'o7',
    titulo: 'Impermeabilização – Obra Comercial RS',
    cliente_id: 'c6',
    vendedor_id: 'v2',
    produto_principal_id: 'p6',
    valor_estimado: 19500,
    fase: 'Fechado Perdido',
    probabilidade: 0,
    data_abertura: '2026-04-01',
    data_prevista: '2026-05-30',
    proxima_acao: 'Registrar motivo e agendar recontato em 90 dias',
    prioridade: 'Baixa',
    produtos: ['p6'],
    motivo_perda: 'Cliente optou por concorrente com menor prazo de entrega',
    atividades: [
      { tipo: 'Ligação', data: '2026-05-29', descricao: 'Cliente informou que fechou com outro fornecedor.', usuario: 'Patrícia Souza' },
    ],
  },
  {
    id: 'o8',
    titulo: 'Argamassas e Cimentos – Reforma Predial BH',
    cliente_id: 'c11',
    vendedor_id: 'v3',
    produto_principal_id: 'p10',
    valor_estimado: 54500,
    fase: 'Proposta',
    probabilidade: 55,
    data_abertura: '2026-05-28',
    data_prevista: '2026-07-31',
    proxima_acao: 'Aguardar retorno após análise interna do cliente',
    prioridade: 'Média',
    produtos: ['p10', 'p1', 'p8'],
    atividades: [
      { tipo: 'Proposta', data: '2026-06-18', descricao: 'Proposta enviada com previsão de entrega em 15 dias úteis.', usuario: 'Felipe Andrade' },
      { tipo: 'Reunião', data: '2026-06-12', descricao: 'Reunião técnica para definição de especificações dos materiais.', usuario: 'Felipe Andrade' },
    ],
  },
  {
    id: 'o9',
    titulo: 'Coberturas Metálicas – Parque Industrial PE',
    cliente_id: 'c12',
    vendedor_id: 'v4',
    produto_principal_id: 'p7',
    valor_estimado: 175000,
    fase: 'Qualificação',
    probabilidade: 40,
    data_abertura: '2026-06-10',
    data_prevista: '2026-09-30',
    proxima_acao: 'Solicitar memorial descritivo do projeto',
    prioridade: 'Alta',
    produtos: ['p7', 'p9', 'p6'],
    atividades: [
      { tipo: 'Ligação', data: '2026-06-24', descricao: 'Segunda conversa. Cliente enviará projeto arquitetônico esta semana.', usuario: 'Camila Torres' },
      { tipo: 'Email', data: '2026-06-12', descricao: 'Apresentação de catálogo de telhas e perfis metálicos.', usuario: 'Camila Torres' },
    ],
  },
  {
    id: 'o10',
    titulo: 'Agregados e Areia – Loteamento GO',
    cliente_id: 'c9',
    vendedor_id: 'v4',
    produto_principal_id: 'p8',
    valor_estimado: 31000,
    fase: 'Prospecção',
    probabilidade: 15,
    data_abertura: '2026-06-24',
    data_prevista: '2026-08-31',
    proxima_acao: 'Enviar tabela de preços e condições de frete',
    prioridade: 'Baixa',
    produtos: ['p8', 'p1'],
    atividades: [
      { tipo: 'Ligação', data: '2026-06-25', descricao: 'Primeiro contato. Cliente iniciando loteamento de 80 lotes.', usuario: 'Camila Torres' },
    ],
  },
  {
    id: 'o11',
    titulo: 'Contrato Trimestral – Reposição MatCon AM',
    cliente_id: 'c10',
    vendedor_id: 'v2',
    produto_principal_id: 'p4',
    valor_estimado: 86000,
    fase: 'Negociação',
    probabilidade: 75,
    data_abertura: '2026-05-05',
    data_prevista: '2026-07-10',
    proxima_acao: 'Revisar cláusula de reajuste do contrato',
    prioridade: 'Alta',
    produtos: ['p4', 'p5', 'p10'],
    atividades: [
      { tipo: 'Reunião', data: '2026-06-23', descricao: 'Revisão de minutas do contrato com equipe jurídica do cliente.', usuario: 'Patrícia Souza' },
      { tipo: 'Email', data: '2026-06-14', descricao: 'Envio de minuta de contrato para análise.', usuario: 'Patrícia Souza' },
    ],
  },
  {
    id: 'o12',
    titulo: 'Expansão – Novos Pontos de Venda Vidal',
    cliente_id: 'c2',
    vendedor_id: 'v2',
    produto_principal_id: 'p1',
    valor_estimado: 58000,
    fase: 'Qualificação',
    probabilidade: 30,
    data_abertura: '2026-06-05',
    data_prevista: '2026-08-20',
    proxima_acao: 'Agendar call com o diretor financeiro',
    prioridade: 'Média',
    produtos: ['p1', 'p3', 'p10'],
    atividades: [
      { tipo: 'Ligação', data: '2026-06-20', descricao: 'Marcos Vidal mencionou abertura de 3 novos pontos no interior.', usuario: 'Patrícia Souza' },
    ],
  },
  {
    id: 'o13',
    titulo: 'Contrato Anual – Cimentos EngBR',
    cliente_id: 'c4',
    vendedor_id: 'v1',
    produto_principal_id: 'p1',
    valor_estimado: 320000,
    fase: 'Fechado Ganho',
    probabilidade: 100,
    data_abertura: '2026-02-01',
    data_prevista: '2026-05-15',
    proxima_acao: 'Programar entregas mensais conforme cronograma',
    prioridade: 'Alta',
    produtos: ['p1', 'p8'],
    atividades: [
      { tipo: 'Email', data: '2026-05-14', descricao: 'Contrato assinado. Primeiro pedido confirmado para junho.', usuario: 'Ricardo Mendes' },
    ],
  },
  {
    id: 'o14',
    titulo: 'Sistema de Drenagem – Residencial Curitiba',
    cliente_id: 'c5',
    vendedor_id: 'v4',
    produto_principal_id: 'p5',
    valor_estimado: 43000,
    fase: 'Proposta',
    probabilidade: 60,
    data_abertura: '2026-06-03',
    data_prevista: '2026-07-25',
    proxima_acao: 'Apresentar proposta técnica completa',
    prioridade: 'Média',
    produtos: ['p5', 'p6'],
    atividades: [
      { tipo: 'Proposta', data: '2026-06-19', descricao: 'Envio de proposta técnica com especificações de tubos e conexões.', usuario: 'Camila Torres' },
      { tipo: 'Reunião', data: '2026-06-11', descricao: 'Visita ao empreendimento para levantamento da rede de drenagem.', usuario: 'Camila Torres' },
    ],
  },
  {
    id: 'o15',
    titulo: 'Reposição Mensal – Distribuidora Alfa',
    cliente_id: 'c8',
    vendedor_id: 'v1',
    produto_principal_id: 'p3',
    valor_estimado: 78000,
    fase: 'Fechado Ganho',
    probabilidade: 100,
    data_abertura: '2026-04-01',
    data_prevista: '2026-05-01',
    proxima_acao: 'Programar entregas da segunda remessa',
    prioridade: 'Alta',
    produtos: ['p3', 'p1'],
    atividades: [
      { tipo: 'Email', data: '2026-04-30', descricao: 'Pedido confirmado. NF emitida e separação em andamento.', usuario: 'Ricardo Mendes' },
    ],
  },
];

const RECEITA_MENSAL = [
  { mes: 'Jan', valor: 285000 },
  { mes: 'Fev', valor: 340000 },
  { mes: 'Mar', valor: 410000 },
  { mes: 'Abr', valor: 375000 },
  { mes: 'Mai', valor: 520000 },
  { mes: 'Jun', valor: 468000 },
];

const TAREFAS_HOJE = [
  { id: 't1', titulo: 'Enviar contraproposta para Horizonte Obras', oportunidade_id: 'o1', responsavel: 'v1', urgente: true },
  { id: 't2', titulo: 'Ligar para EngBR sobre prazos de entrega', oportunidade_id: 'o2', responsavel: 'v1', urgente: false },
  { id: 't3', titulo: 'Enviar amostras de tintas para MatCon', oportunidade_id: 'o3', responsavel: 'v3', urgente: false },
  { id: 't4', titulo: 'Revisar minuta de contrato SuperObra', oportunidade_id: 'o11', responsavel: 'v2', urgente: true },
  { id: 't5', titulo: 'Solicitar memorial descritivo – BuildTech PE', oportunidade_id: 'o9', responsavel: 'v4', urgente: false },
];

// Helpers
function getCliente(id) { return CLIENTES.find(c => c.id === id); }
function getVendedor(id) { return VENDEDORES.find(v => v.id === id); }
function getProduto(id) { return PRODUTOS.find(p => p.id === id); }

function formatCurrency(valor) {
  return new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(valor);
}

function formatDate(dateStr) {
  const [y, m, d] = dateStr.split('-');
  return `${d}/${m}/${y}`;
}

const FASES = ['Prospecção', 'Qualificação', 'Proposta', 'Negociação', 'Fechado Ganho', 'Fechado Perdido'];
